name: Publish to PyPI and TestPyPI

on:
  workflow_run:
    workflows: ["Test & Coverage"]
    branches: [main,v*]
    types: [completed]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-to-pypi:
    needs: [build]
    name: Publish distribution to PyPI
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/fridafuse
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
    needs: [build]
    name: Publish distribution to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/fridafuse
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

  github-release:
    needs: [publish-to-pypi]
    name: Sign with Sigstore and upload to GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        "$GITHUB_REF_NAME"
        --repo "$GITHUB_REPOSITORY"
        --notes ""
    - env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        "$GITHUB_REF_NAME" dist/**
        --repo "$GITHUB_REPOSITORY"
