name: Test & Coverage

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Test & Coverage on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - run: pipx install hatch
    - run: hatch fmt --check
    - run: hatch test -i python=${{ matrix.python-version }} --cover  # matches entries in pyproject.toml
